### ISSUE TITLE
npm package 0.1.4 wrong version?

### ISSUE THREAD

**Issue by SimonDR-Boltzmann** [byjg/jquery-sse#10]
Hi!
I was having an issue similar to https://github.com/byjg/jquery-sse/issues/8 , with the npm package version 0.1.4, but on comparing with master here it seems that it's the 0.1.3 version, could it be there was a mistake in deploy?

**Comment by byjg** [comment]
You are right. The method I created in PR #8 is not there. 

I'll create a new version 0.1.5 by the EOD, ok?

**Comment by byjg** [comment]
I published release 0.1.5. 

Now it contains the code fixing issue #8. Could check if it is working for you?

**Comment by SimonDR-Boltzmann** [comment]
Yes, it works! Thanks for the fast response!

**Comment by byjg** [comment]
No problem. Thank you for letting me know. 

I am closing this issue.
