### ISSUE TITLE
How can I set Headers to authenticate with the URL

### ISSUE THREAD

**Issue by jorgevalbuena56** [byjg/jquery-sse#2]
I am using your library and I need to set some headers to the Event request. How can I do this?

**Comment by byjg** [comment]
Unfortunately the EventSource native does not support custom headers[[1]](http://stackoverflow.com/questions/24272157/eventsource-xhr-headers). I do not rewrite the EventSource object, but I create a fallback to ajax. There are libraries that completly rewrite the EventSource[[2]](http://stackoverflow.com/questions/28176933/http-authorization-header-in-eventsource-server-sent-events) and add this options. 

But this feature is very interesting and I can try do it in another branch. But I'll need you for testing the solution. The implementation I am thinking is: 
- Add to the constructor the parameter CUSTOM Headers 
- If has custom headers the system automatically fallback to Ajax Polling.

It is it OK for you the implementation above and you do some tests, I can do something tonight. 

Let me know.

**Comment by byjg** [comment]
I created the branch 'custom-headers'. Could you test it for me?

**Comment by byjg** [comment]
There is no answer from @jorgevalbuena56 . I did the version 1.0.3 with the custom header. I am closing this issue.
