### ISSUE TITLE
Browsers support, IE

### ISSUE THREAD

**Issue by vnea** [byjg/jquery-sse#5]
Hello,

I want to know if it supports IE/Edge or not.

Thank you !

**Comment by byjg** [comment]
Hi,

This script has been tested in Chrome, Firefox, Safari and Internet
explorer.

Because the script is polyfill even the browser does not have a native
implementation it can reproduce the same behavior .


Em 26 de jun de 2017 1:00 PM, "Victor Nea" <notifications@github.com>
escreveu:

**Comment by vnea** [comment]
Thank you for your fast answer ! :)

**Comment by byjg** [comment]
You're welcome

Em 27 de jun de 2017 4:56 AM, "Victor Nea" <notifications@github.com>
escreveu:
